---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: quarkus-pekko-sa
  namespace: quarkus-pekko
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: quarkus-pekko
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: quarkus-pekko
subjects:
- kind: ServiceAccount
  name: quarkus-pekko-sa
  namespace: quarkus-pekko
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io